
const DATA={
 names:["Lionel","Kaid","Lian","Nero","Ember","Mako","Orion","Cale","Riven","Sora","Vale","Juno"],
 seas:["East Blue","West Blue","North Blue","South Blue"],
 islands:[{name:"Foosha Village",sea:"East Blue",danger:1,desc:"A peaceful ocean village full of young dreams."},{name:"Shells Town",sea:"East Blue",danger:2,desc:"A Marine-controlled town with rising patrols."},{name:"Orange Town",sea:"East Blue",danger:3,desc:"A lively port with rumors and pirate activity."},{name:"Syrup Village",sea:"East Blue",danger:2,desc:"A quiet village where rumors travel fast."},{name:"Loguetown",sea:"East Blue",danger:5,desc:"The town of beginnings and endings."},{name:"Moonveil Island",sea:"Grand Line",danger:6,desc:"A stormy island hiding old secrets."}],
 families:[{name:"Poor Dock Workers",bonus:{beli:100,strength:1},desc:"Your family survives on dock labor and favors."},{name:"Working Fisher Family",bonus:{health:5,speed:1},desc:"Your family knows the sea better than most."},{name:"Merchant Family",bonus:{beli:1000,charisma:1},desc:"Your family trades goods between islands."},{name:"Marine Family",bonus:{discipline:2,marineRep:1},desc:"Justice is discussed at your dinner table."},{name:"Criminal Family",bonus:{sneak:2,infamy:1},desc:"You learn early that law and survival are not always the same."},{name:"Unknown Parents",bonus:{potential:2,willpower:1},desc:"No one knows where you came from. Maybe that matters."}],
 dreams:["Undiscovered","Become Pirate King","Freedom","Justice","Knowledge","Riches","Strongest Swordsman","Protect My People"],
 news:["Red-Haired Pirates spotted near Foosha Village.","A Marine ship has docked at Shells Town.","A rare fruit merchant was seen near Orange Town.","Strange weather patterns seen in the Grand Line.","Bounty activity has increased in the East Blue."],
 weapons:[{name:"Rusty Sword",type:"Weapon",rarity:"Common",power:4,desc:"A worn sword, but better than nothing."},{name:"Flintlock Pistol",type:"Weapon",rarity:"Common",power:5,desc:"A basic pistol used by rookies."},{name:"Graded Blade III",type:"Weapon",rarity:"Rare",power:18,desc:"A reliable graded blade for serious swordsmen."},{name:"Storm Fang",type:"Weapon",rarity:"Legendary",power:35,desc:"A spear forged from storm iron."}],
 items:[{name:"Small Med Kit",type:"Item",rarity:"Common",qty:3,desc:"Restores health."},{name:"Energy Meat",type:"Item",rarity:"Common",qty:5,desc:"Restores energy."},{name:"Log Pose",type:"Key Item",rarity:"Rare",qty:1,desc:"Needed for dangerous sea routes."},{name:"Seastone Fragment",type:"Material",rarity:"Rare",qty:8,desc:"Useful against Devil Fruit users."}],
 fruits:[{name:"Smoke Body Fruit",type:"Logia",rarity:"Epic",power:28,desc:"Become smoke to evade and bind enemies."},{name:"Wolf-Wolf Fruit",type:"Zoan",rarity:"Uncommon",power:13,desc:"Transform into a wolf or wolf hybrid."},{name:"Barrier-Barrier Fruit",type:"Paramecia",rarity:"Rare",power:20,desc:"Create powerful protective barriers."}]
};
